---
# Installation de Docker et Déploiement de l'image
- name: Deploy image Docker
  hosts: vm-dev
  remote_user: 
  gather_facts: false
  become: true

  vars_files:
    - vars.yml

  roles:
    - vm-dev
